---
- name: Install WordPress, a database, nginx, and PHP-FPM
  hosts: all
  # remote_user: user
  become: yes

  roles:
    - common
    - mysql
    - nginx
    - letsencrypt
    - php-fpm
    - wordpress
