- name: install letsencrypt
  apt: name=letsencrypt state=latest

- name: stop nginx to create letsencrypt certificate
  command: service nginx stop

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n -m {{ letsencrypt_email }} --agree-tos -d {{ server_hostname }}
  args:
    creates: /etc/letsencrypt/live/{{ server_hostname }}

- name: Copy nginx configuration for WordPress
  template: src=default dest=/etc/nginx/sites-available/default

- name: Reload nginx to activate specified site
  command: service nginx restart

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n -m {{ letsencrypt_email }} --agree-tos -d {{ server_hostname }} && service nginx reload
